"""empty message

Revision ID: 27cd3992716a
Revises: f6b6d7afb2d0
Create Date: 2022-09-25 21:42:15.950569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cd3992716a'
down_revision = 'f6b6d7afb2d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cartes',
    sa.Column('id_carte', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=True),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.Column('univers', sa.Text(), nullable=True),
    sa.Column('force', sa.Integer(), nullable=True),
    sa.Column('mana', sa.Integer(), nullable=True),
    sa.Column('vitesse', sa.Integer(), nullable=True),
    sa.Column('popularite', sa.Integer(), nullable=True),
    sa.Column('prix', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_carte')
    )
    op.create_table('Joueurs',
    sa.Column('id_j', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('pick_nb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_j')
    )
    op.create_table('CartesJoueurs',
    sa.Column('id_carte', sa.Integer(), nullable=False),
    sa.Column('id_j', sa.Integer(), nullable=True),
    sa.Column('nb_cartes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carte'], ['Cartes.id_carte'], ),
    sa.ForeignKeyConstraint(['id_j'], ['Joueurs.id_j'], ),
    sa.PrimaryKeyConstraint('id_carte', 'id_j')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CartesJoueurs')
    op.drop_table('Joueurs')
    op.drop_table('Cartes')
    # ### end Alembic commands ###
