"""empty message

Revision ID: d417efe424d5
Revises: b71243e2551d
Create Date: 2022-09-25 21:37:34.395660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd417efe424d5'
down_revision = 'b71243e2551d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
