"""empty message

Revision ID: f6b6d7afb2d0
Revises: d417efe424d5
Create Date: 2022-09-25 21:38:55.781957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b6d7afb2d0'
down_revision = 'd417efe424d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
